### ISSUE TITLE
Can we skip getDidAskOnce check on Android?

### ISSUE THREAD

**Issue by hey99xx** [zoontek/react-native-permissions#128]
```
return RNPermissions.check(androidPermission)
			.then(isAuthorized => {
				if (isAuthorized) return 'authorized'

				return getDidAskOnce(permission)
					.then(didAsk => {
						if (didAsk) {
							return shouldShowRationale(androidPermission)
								.then(shouldShow => shouldShow ? 'denied' : 'restricted')
						}
						return 'undetermined'
					})
			})
```

On Android, you have this `getDidAskOnce` check which looks at asyncstorage to determine whether we need to show the permission or not ( use of `shouldShowRationale`), and then return 'denied' or 'restricted' accordingly.

Can I ask why we need this extra step? Would this be easier?:

```
return RNPermissions.check(androidPermission)
			.then(isAuthorized => {
				if (isAuthorized) return 'authorized'

                              return shouldShowRationale(androidPermission)
                                       .then(shouldShow => shouldShow ? 'denied' : 'restricted')
```

Besides avoid the extra round trip to asyncstorage (and thereby not doing I/O), this has one very good advantage that is compatibility with any other permission request. 

To give you context, I am working in a brown field / hybrid app where we have both native and RN views inside the app and intend to use your library. Now if a native view asks for the permission first, and gets "never ask again", your asyncstorage is not populated accordingly, but `shouldShowRationale` would return false either way. So with your current approach, until we at least ask once through RN permissions API, we will always get `undetermined` status from the `check` method.

This should also align with your README

> `undetermined` | user has not yet been prompted with a permission dialog

which in the current implementation obviously considers permission requests through this RN module, but does not consider that permissions can be asked in different parts of the app without RN at all.

**Comment by hey99xx** [comment]
This should also align with your README

>  `undetermined`| user has not yet been prompted with a permission dialog

which in the current implementation obviously considers permission requests through this RN module, but does not consider that permissions can be asked in different parts of the app without RN at all.

**Comment by yonahforst** [comment]
@hey99xx - that's an interesting point. I'm not sure which is better: to never show `undetermined` or to show it when it possibly might actually be `denied`.

**Comment by eeynard** [comment]
Hi guys, I ran into another issue caused by this `getDidAskOnce` check. Since Android 6.0 Google introduced an [Auto Backup](https://developer.android.com/guide/topics/data/autobackup.html) system that backup your local storage on your Google Drive every once in a while. 

The problem is that even after reinstalling the app I had a `restricted` status by default so I wasn't able to get the permission dialog. My point is that I'm not sure that the `didAskOnce` bool should be stored in the AsyncStorage since it can be backed up, the user should be able to start with fresh permissions when reinstalling the app.

In my case I don't need this back up system (which is enabled by default) so by disabling it it should fix this problem but maybe there are people interested in this feature.

**Comment by zoontek** [comment]
@eeynard I will remove this in a future version (breaking changes...).
Temporarily, ou can disable auto backup by setting `android:allowBackup` to `false` in your AndroidManifest.xml

**Comment by Diego-Franco** [comment]
I tried to set false for `AllowBackup` but doesn't work in some devices, is still given me `restricted`
