### ISSUE TITLE
Denying notification permissions does not change permission status to denied

### ISSUE THREAD

**Issue by kyangy** [zoontek/react-native-permissions#166]
**iOS**

Denying notification permissions does not change permission status to `denied` and stays as `undetermined`. Not sure if it's cause I am using `react-native-push-notification` to request permissions but if I allow, it does change to `authorized` but denying it leaves it as `undetermined`.

**Comment by mmarvick** [comment]
I'm running into this one too

**Comment by mmarvick** [comment]
I ran into this issue because I was checking for the permissions outside of `react-native-permissions`, so the value `RNPDidAskForNotification` wasn't getting set. Once I made sure the permissions request was coming from the library, things worked as expected.

**Comment by IgorVanian** [comment]
Yep, using `react-native-push-notification`doesn't work with this library permission check.

**Comment by haofeng123** [comment]
@mmarvick  how to checking for the permissions outside of react-native-permissions , i can't find the value RNPDidAskForNotification

**Comment by mmarvick** [comment]
@haofeng123 you can make the permissions request from the library itself by calling (`Permissions.request('notification,'`...).

We needed to be able to ask for it outside of the library though, so we just log a value ourself. So instead of relying on `RNPDidAskForNotification` being set and checked by the library, we just set our own value in AsyncStorage when we ask for notification permission from the system. Then, we know that if we've shown the system prompt but the permission is not `authorized`, that the user has probably rejected it.

**Comment by stevula** [comment]
Same problem but I'm using [react-native-onesignal](https://github.com/geektimecoil/react-native-onesignal) to ask for notifications permissions. This library looks quite nice but I guess I'll stick to onesignal's permissions checking API for now.

**Comment by cyberjar09** [comment]
> I ran into this issue because I was checking for the permissions outside of `react-native-permissions`, so the value `RNPDidAskForNotification` wasn't getting set. Once I made sure the permissions request was coming from the library, things worked as expected.

I'm facing the same issue, but `Permissions.check()` *is* using the library, still getting `undetermined` instead of `denied` 

anyone fixed this?

**Comment by mmarvick** [comment]
@cyberjar09 do you ever prompt for the permissions dialog before using this library? Perhaps from another library or API?

If you call `enable()` from urban airship's push API for example, their SDK shows the system permission prompt -- but if you do that, `react-native-permissions` has no way to know that the system prompt was already shown. It's only able to know that if you call `request()` from this library (because it has to persist a value in app storage to keep track of that), and never from any other library.

**Comment by cyberjar09** [comment]
> @cyberjar09 do you ever prompt for the permissions dialog before using this library? Perhaps from another library or API?
> 
> If you call `enable()` from urban airship's push API for example, their SDK shows the system permission prompt -- but if you do that, `react-native-permissions` has no way to know that the system prompt was already shown. It's only able to know that if you call `request()` from this library (because it has to persist a value in app storage to keep track of that), and never from any other library.

yes you're right, the previous permission was requested by firebase api in my case, thanks!

**Comment by con4man** [comment]
Still experiencing this issue. Does anyone have a fix?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
