### ISSUE TITLE
Does "restricted" apply to all permission types?

### ISSUE THREAD

**Issue by wootwoot1234** [zoontek/react-native-permissions#18]
I'm trying to understand `restricted`.  Can the `camera` or `microphone` permission return `restricted`?    Can you give me some examples of when `restricted` is returned when getPermissionStatus() is called?

**Comment by yonahforst** [comment]
@wootwoot1234 restricted only really applies to iOS permissions (I should update the documentation to clarify that)

On iOS, it generally means that the user is not able to grant the indicated permission; either because it its not supported by the device or because it has been blocked by parental controls. 

Here's a link to the apple docs describing the different location permission states: https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/c/tdef/CLAuthorizationStatus

**Comment by wootwoot1234** [comment]
Cool.  That clears it up.  I updated the docs with your explanation here: https://github.com/yonahforst/react-native-permissions/pull/20

**Comment by yonahforst** [comment]
thanks! merged
