### ISSUE TITLE
package com.facebook.react.modules.permissions does not exist

### ISSUE THREAD

**Issue by KGALLET** [zoontek/react-native-permissions#19]
Hi, 
I want to use the module in my android project. I did use it in my iOS without problem when it was 0.0.2 release.

When i run `react-native run-android` I got this issue.

![capture d ecran 2016-08-02 a 21 34 47](https://cloud.githubusercontent.com/assets/14168629/17342321/0b2d9002-58f9-11e6-85be-70e1fce30b79.png)

Can someone have this issue too ? 

Thx

**Comment by vincentfretin** [comment]
I guess you need at least RN 0.29 where Android permissions was introduced, it may be good to add the info in the README.

**Comment by KGALLET** [comment]
Ok, updating to RN 0.30 solve my problem. 
Thx @vincentfretin @yonahforst :) 
Closed.

**Comment by yonahforst** [comment]
reopened so I don't forget to update the readme

**Comment by yonahforst** [comment]
thanks for updating the readme, @KGALLET!

**Comment by radko93** [comment]
Getting this on RN 0.31.0, any tips?

**Comment by yonahforst** [comment]
Hrmmm. I was lazy and used an undocumented API 😱 . It probably changed in 0.31.0, I'll have a look.

**Comment by radko93** [comment]
Probably it is my fault since my android project uses older RN version than the version installed from npm (how this is even possible?), but thanks for checking anyway :)

**Comment by yonahforst** [comment]
Ok, no problem. I checked anyways and looks like the API hasn't changed. Closing the issue back out.

**Comment by ekryski** [comment]
FWIW it probably should have been a minor release, since this has a breaking change. Anyone on a version of RN < 0.29.0 had it installed on an npm install.

**Comment by yonahforst** [comment]
@ekryski thanks for bringing this up. I wasn't sure if I did the version numbers right, so I really appreciate feedback here.

Android wasn't supported on previous versions so I didn't think adding it would be considered a breaking change. The old API still works but has deprecation messages. That's why I did it as a minor release (0.1.x -> 0.2.x is minor, right?). Or did you mean it should have been a _major_ release. 

Also, what do you mean here:

>  Anyone on a version of RN < 0.29.0 had it installed on an npm install.

Thanks for educating me on this 🙏🏽

**Comment by ekryski** [comment]
@yonahforst no problem bud. With npm, minor releases < 1.0.0 (ie. 0.1.0) won't get automatically installed. Patch releases will (ie. 0.1.1).

Above 1.0.0 only **major** releases won't be installed automatically, minor and patch releases will.

So if you are < 1.0.0 (which is totally fine especially in RN because shit is changing so much) then just do a minor release for breaking changes. With [feathers](feathersjs/feathers) we don't bump to a 1.0 until we feel like it is "stable". A bit wishy-washy but it's been working well for us so far.

> Android wasn't supported on previous versions so I didn't think adding it would be considered a breaking change. 

I totally understand. How the hell are you supposed to know? Definitely no blame here. The issue was that doing an npm install, brought in references to Facebook's permissions in the Android gradle files, and unless you are v0.29+ of RN it just blows up compiling. So you wouldn't see it if you are only running RN on an iOS device.

Hope that explains things! Really appreciate the hard work! 😄

**Comment by yonahforst** [comment]
@ekryski - Hey dude, thanks for the explanation. I didn't realize that npm treated <1.0.0 and >=1.0.0 differently. Will definitely follow this rule going forward!! thanks again 🍻

**Comment by perusopersonale** [comment]
I'm having this problem too.
npm list say that I'm using RN v0.32.1

**Comment by xwartz** [comment]
I have the same issue, RN v0.36.
