### ISSUE TITLE
 ld: library not found for -lReactNativePermissions

### ISSUE THREAD

**Issue by kbshare** [zoontek/react-native-permissions#206]
Hello!

I use Jenkins archive my project, throw this error:

[31m❌  ld: library not found for -lReactNativePermissions[0m
[31m❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)[0m

I tried many ways, but I couldn't solve the problem.
I found ReactNativePermissions in Libraries, it lost a Physical folders, this is probably the cause of this mistake.

**Comment by tbazko** [comment]
Happens to me too, after upgrading to RN 0.50+

**Comment by anarwade** [comment]
Same here. I'm using RN 0.51.0.
Seems like the android folder is missing

**Comment by zoontek** [comment]
@zhangyaweigithub Why did you ignore the issue template? https://github.com/yonahforst/react-native-permissions/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kbshare** [comment]
@zoontek  oh! my fault!  I'm using RN 0.46, xcode9
@tbazko @anarwade I've solved this question
[31m❌ ld: library not found for -lReactNativePermissions�[0m
�[31m❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)�[0m

Delate the Library "ReactNativePermissions.a" in Xcode-> build phases->Link Binary With Libraries
it will be ok, 
For reference only

**Comment by zoontek** [comment]
@zhangyaweigithub Which version of the lib? :)

**Comment by kbshare** [comment]
@zoontek "react-native-permissions": "^1.0.4",

**Comment by zoontek** [comment]
Try to update to the 1.0.6 (unlink before, link after), because this issue has been fixed.

**Comment by Maxwell2022** [comment]
@zoontek still having the exact same issue with `1.1.0` and RN `0.51.0`

I've downgraded to `1.0.5` and it's working

**Comment by zeh** [comment]
The problem here is that updates _from_ 1.0.5- to anything 1.0.6+ need unlinking and relinking.

Follow the instructions on [1.0.6](https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.6), or simply:

1. If needed, roll back with `npm install react-native-permissions@1.0.5` (or whatever version you used before)
2. Unlink: `react-native unlink react-native-permissions`
3. Update: `npm install react-native-permissions@latest --save`
4. Re-link: `react-native link react-native-permissions`

**Comment by hushicai** [comment]
still happened in react-native-permissions@1.1.1

react-native: 0.48.4
