### ISSUE TITLE
Request for Location Permissions not running at runtime for iOS

### ISSUE THREAD

**Issue by abeddow91** [zoontek/react-native-permissions#233]
Hi, 

I'm trying to put location permission request on click but as soon as I add in the privacy keys to the info.plist the location permission request appears on initial load rather than at runtime. Is there anyway around this so that it only appears on click?

Thanks!

Environment

* React-Native version: 0.50.3
* Platform: iOS
* Device: SE simulator
* react-native-permissions version: 1.0.1

**Comment by andwaal** [comment]
I think I did encounter the same issue, for me the problem was that I startet the react-native Geolocation service in the index.js file of my app, which triggeres the location permission request.

In the last version of RN it possible to disable this behavior by setting [skipPermissionRequests=true](https://facebook.github.io/react-native/docs/geolocation.html#setrnconfiguration), by doing this RN will not request permission on your behalf and your free to request it when you want.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
