### ISSUE TITLE
Your app still uses the "prefs:root=" non-public URL scheme, which is a private entity.

### ISSUE THREAD

**Issue by Sebastien-Lampazona** [zoontek/react-native-permissions#269]
Hello,

I'm using your lib and many other, but since Monday, i try to send my app to App Store but i have continuously that error :

> Your app still uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.￼
> 
> Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

I've searched everywhere i can't find that prefs:root=, but in react-native-permission i've found UIApplicationOpenSettingsURLString.

Is it possible, that method can reject app ?

Thank you for your feedback.

**Comment by kinjalravel** [comment]
facing exactly the same issue 

Guideline 2.5.1 - Performance - Software Requirements


Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

**Update:1** 
Found that it's actually issue of another library in project https://github.com/solinor/react-native-bluetooth-status/issues/25

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
