### ISSUE TITLE
Weird behaviour when answering "Allow once" for location permission on iOS 13

### ISSUE THREAD

**Issue by henrikland** [zoontek/react-native-permissions#379]
# Question

I noticed that the behaviour when asking for location permission on iOS 13 is a bit confusing, and was wondering if it's by design or a bug.

If you request permission for `LOCATION_ALWAYS` and answer "Allow once", you will get a `CLAuthorizationStatus` value of `authorizedWhenInUse` back. This status is then mapped to `RESULTS.BLOCKED` in `RNPermissionHandlerLocationAlways`. This doesn't make sense to me.

In the project I'm working on I've added a patch using `patch-package` that adds `RNPermissionStatusAuthorizedOnce` to the `RNPermissionStatus` enum, and a corresponding `RESULTS.ONCE`.

In our app we then treat this result as a special case where we can use the users current location for the duration of the session. But as I said above, I wonder if there is a reason why "Allow once" is not handled in this way in this module?

Thanks!

**Comment by zoontek** [comment]
This is by design to avoid handling each iOS version differently, and it's mapped on the iOS `requestAlwaysAuthorization` logic (https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization?language=objc).

To perform a good `LOCATION_ALWAYS` request, you have to perform a `LOCATION_WHEN_IN_USE` check just after if the result is `RESULTS.BLOCKED`. It make sense on iOS 13, but also on iOS 11 & 12.

#### On iOS >= 13:

<img src="https://developer.apple.com/design/human-interface-guidelines/ios/images/requesting-permission_2x.png" width="50%" />

- `Allow while using app` grant a `Provisional Always` authorization (`RESULTS.GRANTED`). Your app is allowed to request location during the user session, then the user will be prompted if you request his location in the background (`X has been using your location in the background. Do you want to continue allowing this?`)
- `Allow once` (grant a `Temporary When in Use` authorization) -> `RESULTS.BLOCKED` -> then check `LOCATION_WHEN_IN_USE` -> `RESULTS.GRANTED`
- `Don't allow` -> `RESULTS.BLOCKED`

#### On iOS <= 12:

<img src="https://developer.apple.com/design/human-interface-guidelines/ios/images/RequestPermission-example3_2x.png" width="50%" />

- `Always allow` -> `RESULTS.GRANTED`
- `Only while using the app` -> `RESULTS.BLOCKED` -> then check `LOCATION_WHEN_IN_USE` -> `RESULTS.GRANTED`
- `Don't allow` -> `RESULTS.BLOCKED`

If it's help, you can create two wrapper functions:

```ts
type LocationPermissionStatus =
  | 'unavailable'
  | 'denied'
  | 'blocked'
  | 'always'
  | 'whenInUse';

async function checkLocationAlways(): Promise<LocationPermissionStatus> {
  const alwaysStatus = await check(PERMISSIONS.IOS.LOCATION_ALWAYS);

  if (alwaysStatus === RESULTS.GRANTED) {
    return 'always';
  }

  const whenInUseStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
  return whenInUseStatus === RESULTS.GRANTED ? 'whenInUse' : alwaysStatus;
}

async function requestLocationAlways(): Promise<LocationPermissionStatus> {
  const alwaysStatus = await request(PERMISSIONS.IOS.LOCATION_ALWAYS);

  if (alwaysStatus === RESULTS.GRANTED) {
    return 'always';
  }

  const whenInUseStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
  return whenInUseStatus === RESULTS.GRANTED ? 'whenInUse' : alwaysStatus;
}
```

**Comment by henrikland** [comment]
Alright, I get it. It just feels like bad UX to request a different permission immediately if the user answers "Allow once", but maybe that is what you are forced to do in this case. We will probably keep our patch and hope that Apples API changes in the future.

**Comment by zoontek** [comment]
@henrikland You don't have to request `WHEN_IN_USE` after `ALWAYS`, only check it.

**Comment by henrikland** [comment]
Ah of course. I think I need to go home now, my brain is fried apparently. :)
Thanks a lot for the help!

**Comment by zoontek** [comment]
@henrikland  No problem 😄
