### ISSUE TITLE
2.0.7 has broken TS types

### ISSUE THREAD

**Issue by elektronik2k5** [zoontek/react-native-permissions#386]
# Bug

I just upgraded from 2.0.6 to 2.0.7 and the TS types are broken:
```shell
error TS7016: Could not find a declaration file for module 'react-native-permissions'. '/home/[redacted]/node_modules/react-native-permissions/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-permissions` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-permissions';`
```

 Looking at the installed `package.json`:
```json
"types": "lib/typescript/src/index.d.ts",
```
While the directory tree looks like so:
```shell
tree ./node_modules/react-native-permissions/lib/typescript 
./node_modules/react-native-permissions/lib/typescript
├── constants.d.ts
├── index.d.ts
└── types.d.ts
```
As you can see, the problem is in the `package.json` value of the `"types"` property.
https://github.com/react-native-community/react-native-permissions/commit/0276fc8de009e4e967086163721a1faa0f85b13f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L19

## Environment info

Latest TS: `3.7.3`

Library version: `2.0.7`

## Steps To Reproduce

1. Install v2.0.7
1. Try to import anything in TS
1. Error as seen above
1. ???
1. PROFIT!!!

Describe what you expected to happen:

1. It should work

## Reproducible sample code

Once I reverted to 2.0.6 everything started working again.

**Comment by zoontek** [comment]
@elektronik2k5 Sorry about this! I published a new version: https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.8

The path was wrong since the beginning, but before that, metro resolved `src/index.ts`: https://github.com/react-native-community/react-native-permissions/commit/0276fc8de009e4e967086163721a1faa0f85b13f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L18. Which caused https://github.com/react-native-community/react-native-permissions/issues/335 for non-TS users.

Which means `react-native-netinfo` has exactly the same issue (they use Bob too), I might warn them: https://github.com/react-native-community/react-native-netinfo/blob/master/package.json#L5

**Comment by elektronik2k5** [comment]
Thanks for the quick fix!
