### ISSUE TITLE
android can not link the library

### ISSUE THREAD

**Issue by keung725** [zoontek/react-native-permissions#40]
After following the android linking guide, can not link the library

React Native 0.33

error:
react-native-permissions:compileReleaseJavaWithJavac FAILED

**Comment by cvongrim** [comment]
Same issue for me. Also on React Native 0.33

**Comment by StellwagJo** [comment]
Having same issue with:
- react-native: 0.34.0
- react-native-permissions: 0.2.5

**Comment by darkrishabh** [comment]
Same with me

**Comment by yonahforst** [comment]
I've had to put my react-native apps on hold for a while to work on a new project. Because of this, I haven't been keeping up to date with the latest RN and iOS changes. I'll be picking this back up in January '17, but in the meantime, I would welcome pull requests if anyone has a solution.

Sorry to leave you guys hanging... :/

**Comment by keung725** [comment]
anyone can update it?

**Comment by mprothero** [comment]
Adding:
`import com.joshblour.reactnativepermissions.ReactNativePermissionsPackage;`
to MainApplication.java worked for me.

**Comment by xwartz** [comment]
@Michaelprothero  It didn't work for me.

**Comment by yonahforst** [comment]
@xwartz  - are you still experiencing this issue in the latest RN (0.40.0 ATM)

**Comment by yonahforst** [comment]
@xwartz - closing for now, if you're still experiencing this issue, please reopen
