### ISSUE TITLE
Permission is `granted` even if it's not

### ISSUE THREAD

**Issue by dzek69** [zoontek/react-native-permissions#403]
# Bug

On Xiaomi Redmi Note 3 (MTK version), with MIUI 9.3 (build 8.1.18) and Android 5.0.2 when I accept or denied camera access it's always detected as `granted`.

## Environment info

```
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 3.31 GB / 15.89 GB
  Binaries:
    Node: 10.18.1 - C:\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Apps\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 2.0.9

## Steps To Reproduce

Use sample code.
Result:
- No camera request dialog is shown
- Code "passes through" all `await`s instantly, returning "granted"
- Console output:
```
android.permission.CAMERA
1 granted
2 "granted"
```
Describe what you expected to happen:

1. Request dialog should be shown
2. Code should await for decision

This is probably older-Xiaomi-phones behavior, when I'm using `react-native-camera` package - the dialog to give access to camera isn't "standard" Android dialog, but a custom one ( screenshot: https://i.imgur.com/DvYrtkR.png ) - but it's there, so I guess it's possible to overcome this issue.

## Reproducible sample code

```javascript
            const camPermission = Platform.select({
                android: PERMISSIONS.ANDROID.CAMERA,
                ios: PERMISSIONS.IOS.CAMERA,
            });
            console.log(camPermission);
            const resss = await Permissions.request(camPermission);
            console.log("1", resss);
            const result = await Permissions.check(camPermission);
            const isLocked = result !== RESULTS.GRANTED;
            console.log(2, result);
```

**Comment by zoontek** [comment]
> Android 5.0.2

Ih, this is odd, because Permission API only is available on Android 6+. Before that, the request were made at app install on the Play Store and we have to accept all of them at once.

See "Runtime requests": https://developer.android.com/guide/topics/permissions/overview

So it might be a custom management?

**Comment by zoontek** [comment]
Ok I found some infos, it is specific to Xiaomi https://stackoverflow.com/questions/46263727/check-permissions-on-xiaomi-device-with-a-version-below-api-23

> You don't need to check permissions for api level < 23. In xiaomi phone of api level less than 23, the system asks for permission itself before it is used.

`react-native-camera` works for that case because its enable the camera…something this lib doesn't do 😕

**Comment by dzek69** [comment]
The bad thing is having always `granted` , because the app will behave incorrectly because of that
Of course having it always as `rejected` wouldn't help with anything too.

Maybe Xiaomi provides some custom API for that?

Thanks for your research so far 👍

**Comment by zoontek** [comment]
Of course it's bad, but it's the supposed correct answer (Xiaomi seems to be one of the few exceptions)

A custom API seems to exists, but I need to check how much devices marketshare still have MIUI with Android < 6. It might a very small number.

https://stackoverflow.com/questions/39462254/how-to-ask-for-permissions-in-miui-pre-marshmallow

**Comment by zoontek** [comment]
I'm afraid it's not worth it to integrate such non-standard API for a small bunch of devices. But it's a bit of a falsy issue since the lib first returns `granted`, then you have to mount the camera and after that MIUI will request runtime permission by itself (without even handling it).

It will not prevent these small bunch of users from using your app 🙂

If you want to do more than this, a solution could be to use [react-native-device-info](https://github.com/react-native-community/react-native-device-info) + [Platform](https://facebook.github.io/react-native/docs/platform-specific-code#platform-module) to check if it's a Xiaomi on Android < 6.

**Comment by dzek69** [comment]
That's fair, thank you for your research and comments 👍
