### ISSUE TITLE
What is `backgroundRefresh` in version 2?

### ISSUE THREAD

**Issue by vvusts** [zoontek/react-native-permissions#433]
In v1. of the library there was check for `backgroundRefresh` permission:
`Permissions.check('backgroundRefresh')`
I am switching to v2.x and I don't know what is alternative for this not as I don't see this permission in a doc?

**Comment by zoontek** [comment]
Background refresh is not a valid permission since it's not requestable, so it has been removed. Check this issue: https://github.com/react-native-community/react-native-permissions/issues/423

If you use `react-native-background-fetch`, you can check its `status`: https://github.com/transistorsoft/react-native-background-fetch#methods
