### ISSUE TITLE
Error: react-native-permissions: NativeModule.RNPermissions is null.【android】

### ISSUE THREAD

**Issue by kettyy** [zoontek/react-native-permissions#457]
# Bug

## Environment info

`react-native info` output:

```bash
"react-native": "0.62.1",
"react-native-permissions": "^2.1.3",
```

Library version: x.x.x

## Steps To Reproduce

1.cd android && ./gradlew clean
2.yarn android
...

**Comment by i-m-aman** [comment]
Why this issue is closed? I am getting the same error.

**Comment by mikehardy** [comment]
@i-m-aman because it is is the first and most common error when integrating native modules in react-native projects and is not a problem with this module. 

It's terribly repetitive https://github.com/react-native-community/react-native-permissions/issues?q=is%3Aissue+RNPermissions+is+null+is%3Aclosed

There is information in those I believe, but basically your auto-linking is not done correctly or your build has some stale cached elements or similar? If you can reproduce with the example then the module has a problem

**Comment by zoontek** [comment]
@i-m-aman Because the issue template was empty. This issue has already been treated a bunch of times, you can search for duplicates to find your answer.

**Comment by i-m-aman** [comment]
My apologies @zoontek @mikehardy
I had to manually link the module.
Actually my issue was If I npm install the package from my main React Project, it automatically links. But I have react-native-permissions in my ReactNative SDK which I am using in the main Project. Somehow, it doesn't auto links in the latter case. So, I manually link in separate Android and IOS.

Thanks, @zoontek for replying. This module really helped me to develop a react native SDK in very less time.

**Comment by jessanKhan** [comment]
@zoontek  This issue is not fixed for expo cli. please help

**Comment by zoontek** [comment]
> @zoontek This issue is not fixed for expo cli. please help

This package does not support Expo. Use https://docs.expo.io/versions/latest/sdk/permissions

**Comment by jessanKhan** [comment]
@zoontek Thanks for the confirmation
