### ISSUE TITLE
Does the permission obtained by this library have shutdown permission？

### ISSUE THREAD

**Issue by Shuo-Mr** [zoontek/react-native-permissions#496]
# Feature request
-Does the permission obtained by this library have shutdown permission？I learned that this permission requires root and Android development. But as a developer of react native, I'm not necessarily familiar with Android development.

## Why it is needed

At present, I need to use this function in my development, but there is very little related information. When I see that the library is associated with it, I ask whether to add it or provide directions. In fact, even if it is updated, it is estimated that I will not be able to use it.

## Possible implementation

What I've learned so far is that root privileges need to be configured, along with some other configuration. Because I'm not familiar with Android development, I can't give too much advice.

### Code sample
At present, I use Android TV to remotely control TV shutdown or restart. It seems that some set-top box development also has similar functions, which I think is quite common.

Finally, thanks to everyone who is open source.I'm going to keep learning.

**Comment by mikehardy** [comment]
Obtaining root on android is generally not supported by any normal framework anywhere as far as I know because it breaks all the security for a device

If you are related to a manufacturer, you may get special privileges because you deliver the firmware of the Android operating system to the device and thus can have your app installed as a "system app", where it can have the permissions you need already as an assumption

https://stackoverflow.com/questions/14065842/obtain-the-permission-of-shutdown-or-restart-in-android

There is no point I think in adding it here, because either you're a device manufacturer and know you have it already, or you can't get it

**Comment by Shuo-Mr** [comment]
Thank you. I get it. I should contact the equipment manufacturer

**Comment by mikehardy** [comment]
Sincere good luck - there are definitely use cases for it as you mention with TV, I'm sure the set-top box developer coordinates with the app developer to install the app as a system app, and in the meantime you can play with it / test it by unlocking bootloaders and installing magisk or similar to root the device so you can install your app as a system app that way. Cheers
