### ISSUE TITLE
'ask every time' returns `RESULT.BLOCKED`

### ISSUE THREAD

**Issue by eatnug** [zoontek/react-native-permissions#517]
# Question

using react-native 0.63.2, on android simulator Pixel3, x86, Android 11, API 30. 

checking `Ask every time` in `App Info - Permissions - Location` doesn't makes the permission status of `android.permission.ACCESS_FINE_LOCATION` to `denied` which is a status that can be questionable.

**Comment by zoontek** [comment]
Android 11 is not supported yet.

**Comment by eatnug** [comment]
thx :)

**Comment by satya-imaginea** [comment]
Still the feature is not supported as per the above PR. I tried and have the issue i.e getting RESULT.BLOCKED status
 I used     "react-native-permissions": "^3.2.0",

- [ ] Support Ask every time feature on Android

**Comment by mahadevsempire** [comment]
Still ? are you kidding me...

**Comment by mikehardy** [comment]
@mahadevsempire I don't believe anyone is trying to kid you. Exactly what feature do you need that is not working? Are you prepared to work to make the feature work? If not, please reflect on the "are you kidding me" stance, as using open source software means you are not the user, you are the developer

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

etc

**Comment by zoontek** [comment]
@satya-imaginea @mahadevsempire The current Android permission system is broken and this cannot be done with a good UX. We have two choices here and I think the current implementation is the less painful for the user. I'm explaining myself.

![permissions diagram](https://developer.android.com/images/training/permissions/workflow-runtime.svg)

[**👉 Android documentation**](https://developer.android.com/training/permissions/requesting)

How does Android permission system works?:
- First we check the permission status using `checkSelfPermission`. it will return `PERMISSION_GRANTED` (we can use the feature) or `PERMISSION_DENIED` (we can't use the feature but we don't know if the permission is requestable or not)
- If it returns `PERMISSION_DENIED`, we can call `shouldShowRequestPermissionRationale`, which will return `true` or `false`:
  - `true`: the user never requested the permission **or** the permission is not requestable anymore
  - `false`: the app requested the permission once, the user denied it but it's still requestable

Making this step pretty useless for knowing if the permission is requestable or not.

The only moment where we can determine if the permission is requestable is on [`onRequestPermissionsResult`](https://github.com/zoontek/react-native-permissions/blob/3.2.0/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java#L408) invocation,  because if `shouldShowRequestPermissionRationale` returns `false` after a request (not a check!), it means that the user saw the request prompt, deny it (and checked never ask again or it was the second time he denies it on Android >= 11), so it's not needed to show a rationale anymore ([link](https://github.com/zoontek/react-native-permissions/blob/f7a041c282b8cb855f9ae8912ee49db339e53684/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java#L277), so we know it's not requestable anymore.

Use that, then! OK, we can use that until the app is alive (by keeping a `map<permissionName, isRequestable>` variable for example). But after a restart, when calling `checkSelfPermission` we will be stuck in a state where the result will be `PERMISSION_DENIED` and `shouldShowRequestPermissionRationale` will returns `false`…which means what? Has the permission never been requested **or** has the permission been requested and is not requestable anymore?

For that, we have **no other choice** than storing a `boolean` value in the app preferences (wiped when app permissions are wiped too) mentioning that at some point, the permission has been requested and is now non-requestable. The principal issue with this is that if someone deny and block a permission request, go to the app setting and select "Ask next time", this `boolean` will still be `true` = that the permission is non-requestable… This of course does not happen when the user grant the permission in the app settings since `checkSelfPermission` will returns `PERMISSION_GRANTED` before the boolean check in that case.

So, like I said, we have two choices here:
- Doing that and there is this one edge case (the user has to first block the permission, then goes to settings, not for granting it but for checking "Ask next time")…But at least calling the `check` method works, even after an app restart.
- Making `check` returning a `boolean` on Android (since we cannot determine if the permission is requestable, only if it's granted)
  - `true`: The permission is granted, hooray!
  - `false`: The permission is denied. But is it still requestable? We don't know. So, in doubt, we display an UI mentioning the permission "Request" and a nice button. And we will have to wait for the user to press that button to know if the permission was requestable or not. Maybe the user already denied and blocked it before? It will be impossible to display a nice UI with explanations about why it's needed, how to grant it and a "Go to app settings" button in the first place instead - making this super weird.

So…it's Google fault on this one. We couldn't do shit without breaking the `check` function.

[Related issue on StackOverflow](https://stackoverflow.com/questions/32347532/android-m-permissions-confused-on-the-usage-of-shouldshowrequestpermissionrati/52596674)

**Comment by zoontek** [comment]
@mahadevsempire so next time, be polite.

**Comment by hupptechnologies** [comment]
@zoontek I have one question that in some phone we are trying to prompt the permission request (fine and background both) but it's blocked without even asking so it's not supported on the Android >= 11 ? 

Here is my code what i am trying, our app needs to force user to give location access all time.

```
const permissions = [
    PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
    PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION
];
checkMultiple(permissions)
    .then((statuses) => {
        const inUse = statuses[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === 'granted';
        const allTime = statuses[PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION] === 'granted';
        if (inUse && allTime) {
            resolve();
            return;
        }
        requestMultiple([
            PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
            PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION
        ]).then((result) => {
            const inUsePermission = result[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === 'granted';
            const allTimePermission = result[PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION] === 'granted';
            if (inUsePermission && allTimePermission) {
                resolve();
                return;
            }
            if (allTimePermission === false) {
                reject(new Error('Background location permission denied'));
                return;
            }
            reject(new Error('Location permission denied'));
        });
    });
```

**Comment by mikehardy** [comment]
@hupptechnologies  you report a problem and say:

> in some phone

...that implies it works in some other phone? You don't specify any details / example of what phones may work, what phones you observe failure

You don't include how you're handling things in `AndroidManifest.xml`, perhaps you are missing the permission?

I have success on Android 11.

**Comment by zoontek** [comment]
@hupptechnologies https://developer.android.com/training/location/permissions#approximate-request

Try adding `ACCESS_COARSE_LOCATION` (in your `AndroidManifest` + `checkMultiple` and `requestMultiple`). It seems that you **have to** offers the possibility to users to grant only approximate position.

**Comment by hupptechnologies** [comment]
@mikehardy Yes it's only with some OEM phones like Vivo, Xiaomi and doesn't happen with all OEM phones.

@zoontek Below are the permissions that i have already related to location in the AndroidManifest.xml and will try adding `ACCESS_COARSE_LOCATION` in the `checkMultiple` and `requestMultiple` and see what happens.

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```

**Comment by hupptechnologies** [comment]
> @hupptechnologies https://developer.android.com/training/location/permissions#approximate-request
> 
> Try adding `ACCESS_COARSE_LOCATION` (in your `AndroidManifest` + `checkMultiple` and `requestMultiple`). It seems that you **have to** offers the possibility to users to grant only approximate position.

@zoontek I tried but that too resulted in denied because of `ACCESS_BACKGROUND_LOCATION` is there is way that asking permission ACCESS_BACKGROUND_LOCATION works fine in all devices?

**Comment by DonRyu** [comment]
Can I refresh the app when user choose 'ask every time ' at setting at block situation? I think some app's did that but I don't know how to do....

**Comment by zoontek** [comment]
> Can I refresh the app when user choose 'ask every time ' at setting at block situation? I think some app's did that but I don't know how to do....

You can use AppState to check permissions when the app gain focus

**Comment by DonRyu** [comment]
> > Can I refresh the app when user choose 'ask every time ' at setting at block situation? I think some app's did that but I don't know how to do....
> 
> You can use AppState to check notifications when the app gain focus

Thanks zoontek!!

I am afraid I still can't understand 'to check notifications when the app gain focus' means....
The notification means the permission rationale dialog?
Sorry
AppState can tell the app is in foreground or background..... I don't know how to make ask every time select refresh exactly....

**Comment by zoontek** [comment]
@DongHeonRyu To check permissions* (typo)
