### ISSUE TITLE
Permissions Handling on Xiaomi devices

### ISSUE THREAD

**Issue by devWaleed** [zoontek/react-native-permissions#554]
# Feature request

Provide special permissions support for Xiaomi devices.

If your app needs Overlay, Show over lockscreen permissions, there is no way to request those permissions anywhere. We have to go to other packages for these two permissions, there should be a unified package for all permissions need.

## Implementation Help

These links may help you implement it:

https://stackoverflow.com/questions/36123349/how-to-open-draw-overlay-permission-popup-in-miui

https://stackoverflow.com/questions/59518471/enable-special-permissions-by-default-on-xiaomi-mi-phone

**Comment by zoontek** [comment]
@devWaleed Hi. I'm not sure this package should support non standard permissions.

**Comment by devWaleed** [comment]
@zoontek I think it should have all Android & iOS permissions. I am working on a VOIP app and in Xiaomi devices lockcscreen permissions are not working like other Android devices.

**Comment by zoontek** [comment]
@devWaleed I think we should stick to the base system permissions on this repository. Maybe a fork for non-standard permissions like Xiaomi ones is more appropriate (otherwise it's too hard to maintain)

**Comment by Vamsi-Rayapati** [comment]
> @zoontek I think it should have all Android & iOS permissions. I am working on a VOIP app and in Xiaomi devices lockcscreen permissions are not working like other Android devices.

I am also having same issue is it resolved

**Comment by mikehardy** [comment]
I think MIUI should in general not be encouraged to do this (or any of the wide variety of other things they do that breaks AOSP) but you may find this useful https://reactnative.dev/docs/linking#sendintent-android in combination with the stack overflow stuff above, since you have to send users to a special screen anyway, that's how you do it.

Use patch-package to add whatever non-AOSP perms a broken vendor has decided to use to the map here and you'll probably be functioning https://github.com/zoontek/react-native-permissions/blob/fcfa37c95fb6f6529f5ea7567f38c1dc5079d2a6/src/permissions.android.ts#L4
