### ISSUE TITLE
Returns Block in android even if the permission is granted in the settings

### ISSUE THREAD

**Issue by ibingdian** [zoontek/react-native-permissions#565]
Returns Block in android even if the permission is granted in the settings !!!!!!!!

## Environment info
Library version: 
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-permissions": "^3.0.0",

## Steps to reproduce
1. first，blocked the permission ；
2. then, and open the permission in system settings;
3. last,check or request the permission , but the result is always BLOCKED.

Describe what you expected to happen:

 1. after open the permission in system settings, then i check or request the permission, the result should not BLOCKED!!!!!

## Reproducible sample code

    check(permission)
      .then(result=>{
        console.log("check The permission is "+result);
        switch (result) {
          case RESULTS.UNAVAILABLE:
          case RESULTS.LIMITED:
          case RESULTS.GRANTED:
          case RESULTS.BLOCKED:
            callback(result.toString());
            break;
          case RESULTS.DENIED:
            request(permission).then(ret => {
              console.log("request The permission is "+result);
              if (ret===RESULTS.GRANTED){
                callback(ret.toString());
              }else {
                console.log("The permission is "+ret);
              }
            }).catch(err => {
              console.log("err " + err.toString());
            });
            break;
        }
      }).catch(err=>{
      console.log("err " + err.toString());
    });

**Comment by ibingdian** [comment]
the phone is XiaoMi MI 9 、android 10

**Comment by zoontek** [comment]
@ibingdian First, hello. This is a known issue: https://github.com/zoontek/react-native-permissions/releases/tag/3.0.0 (see `Known issue`). This is an issue with the platform itself.

**Comment by nkulic** [comment]
> @ibingdian First, hello. This is a known issue: https://github.com/zoontek/react-native-permissions/releases/tag/3.0.0 (see `Known issue`). This is an issue with the platform itself.

Is that the same issue as mine? When I'm requesting multiple permissions, and this is what is happening:

**First case:**
1. First request call - I grant permission for camera and deny permission for location
- Good and expected output: `DENIED` 

2. Second request call - I press deny and do not ask again for location
- Bad and unexpected output: `DENIED` (should be `BLOCKED`)

**Second case:**
1. First request call - I deny permission for camera and grant permission for location
- Good and expected output: `DENIED` 

> 

2. Second request call - I press deny and do not ask again for camera
- Good and expected output: `BLOCKED`
```
      const results = await requestMultiple([
        PERMISSIONS.ANDROID.CAMERA,
        PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ]);

      if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.GRANTED &&
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.GRANTED
      ) {
        console.log("GRANTED");
      } else if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.BLOCKED ||
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.BLOCKED
      ) {
        console.log('BLOCKED');
      } else if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.DENIED ||
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.DENIED
      ) {
        console.log('DENIED');
      } else {
        Alert.alert('ERROR');
      }
```

**Comment by zoontek** [comment]
@nkulic What you describe has been fixed in the latest release.

**Comment by siemya** [comment]
Hey @zoontek what's the status of the main issue?

**Comment by zoontek** [comment]
@siemya It seems that Google don't solved it yet. But currently updating the status to `GRANTED` will work, only `Ask me next time` on Android 11 is broken.

And that's because the Android permission system have a completely broken design. Let me explain:
- If the permission is requestable, the status is equal to `DENIED`, so you can call `check` or `request`. It will stay `DENIED` if the user doesn't tick `Never ask again`
- If the user tick `Never ask again`, there is no clean API to determine it, but a trick exists: detecting `shouldShowPermissionRationale`. If it return `false`, the promise will return `BLOCKED` (see https://blog.usejournal.com/method-to-detect-if-user-has-selected-dont-ask-again-while-requesting-for-permission-921b95ded536). As there is no way to get this value expected just after the request, you have to store the result (ex: in `SharedPreferences`)
- If we don't do this, the permission system will return `DENIED` after that, but the permission will not be requestable.
- When you update the permission value in app settings, if you set it to `GRANTED`, it will works (see https://github.com/zoontek/react-native-permissions/blob/master/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java#L241), but if you set it to `Ask me next time`, it will not, because the app can't guess that's it's requestable again (`DENIED` +  it's flagged as blocked in `SharedPreferences`)

More infos: https://developer.android.com/training/permissions/requesting

**Comment by zoontek** [comment]
But switching from `DENIED` or `BLOCKED` to `GRANTED` currently works perfectly. Try it with the example app on the repository.

**Comment by BhaveshShadija1313** [comment]
@zoontek returns block in android even if the permission set ask every time in the settings.
step to check issue : 
when asking permission Don't tap any permission just click on back button.
Tap on setting>permissions>camera set as "Ask every time".
again check permission at that time getting block status instead of denied from checkMultiple method

**Comment by rupalpatel0008** [comment]
Having the same issue.

**Comment by ivankdev** [comment]
same issue for "ask every time" on android  - it returns blocked

**Comment by gaurigarg97** [comment]
i am facing the same issue.. permission is granted for android but still coming as denied. has anyone find any solution?

**Comment by zoontek** [comment]
I published a beta to "fix" this issue: https://github.com/zoontek/react-native-permissions/pull/696, explaining how the current Android permission system is broken and which compromise will be probably made until Google fixes it. Feel free to give your feedbacks.

**Comment by pke** [comment]
@ibingdian does this release fix your problem? I am stll getting "blocked" in requestPermission although its allowed via app settings
