### ISSUE TITLE
Make the library actually unified

### ISSUE THREAD

**Issue by ge0rg** [zoontek/react-native-permissions#567]
Hi,

after reading the project description, I was intrigued, as I was actually looking for a *unified* permissions management library, that would abstract away the different platform details and allow the app developer to focus on the actual app.

May I suggest the following improvements to accomplish that goal?

1. Have an exported superset of all permissions supported on any of the platforms as PERMISSIONS, i.e. PERMISSIONS.READ_CONTACTS that would internally map to READ_CONTACTS on Android but to CONTACTS on iOS and on Windows. WRITE_CONTACTS would map to WRITE_CONTACTS on Android, but to CONTACTS on iOS.

2. Permissions that do not exist on a platform will return GRANTED or UNAVAILABLE, depending on whether the respective functionality is implemented.

3. Have a unified flow diagram for all platforms, so that the app developer only needs to implement one flow

4. (Optionally) create a helper method `checkAndRequest(permission, rationale)` that will check for a given permission, request it if needed, and open the app settings dialog if it was rejected by the user before.

**Comment by zoontek** [comment]
@ge0rg Hi,

1. It's way too hard to unify permissions across platform. Some of them have a specific flow (ex: location, notifications, photo library…), so I'd rather let the developer having full power to check / request them the way he want.
2. That's already the case
3. That's already the case (it's in the README - and except some specific rules on iOS they are basically the same)
4. `check`,  `request` and `openSettings` all return a `Promise`. Chaining them is naturel by design and this kind of function can be done in user-land code (and it fits with the API design in 1.: this lib is much more a set of functions to handle app permissions, not a tentative of abstract platforms logic too much 🙂)
