### ISSUE TITLE
Am I the only one who think that "Denied" is wrong state for the unknown status?

### ISSUE THREAD

**Issue by gran33** [zoontek/react-native-permissions#573]
## Summary

Denied means - "I refuse" 
Denied doesn't mean - "I still don't know, you can ask me if you want"

Form oxford - 
_"State that one refuses to admit the truth or existence of."_

I think it should be Unknown or Undefined or Null...

## Steps to reproduce
See denied result 🤷‍♂️

**Comment by zoontek** [comment]
I agree, but it's the default Android wording 🤷🏻‍♂️

**Comment by zoontek** [comment]
https://reactnative.dev/docs/permissionsandroid

https://developer.android.com/training/permissions/requesting

**Comment by gran33** [comment]
I don't see any reference that doing such misleading terminology...
All your link shows that "denied" is when the user been asked and says no, explicitly.

**Comment by gran33** [comment]
Anyway, thanks for an awesome library and well-typed as well!

**Comment by zoontek** [comment]
> I don't see any reference that doing such misleading terminology...
> All your link shows that "denied" is when the user been asked and says no, explicitly.

![BD5BB7C8-C3EE-48D1-B7E0-548FD63E479B](https://user-images.githubusercontent.com/1902323/110240685-6ba33700-7f4d-11eb-87ef-22c138edb344.png)

No, just try using React Native `PermissionAndroid` module or native `checkPermission`, if you never asked it, it will return `denied`.

Which could somehow make sense because the access to the feature is `denied`… Even if I think `undetermined` makes more sense, the goal is also not to confuse users with new wording / jargon.
