### ISSUE TITLE
RESULTS.LIMITED -- Is this type of permission result applicable to both Android and iOS?

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#603]
Out of all permissions results mentioned in the Docs, `RESULTS.LIMITED` seems strange which I have never come across. In my app I am using `Camera, Microphone, Location services, Photo Library, Storage.` For all these permissions I have seen `RESULTS.UNAVAILABLE, RESULTS.DENIED, RESULTS.GRANTED, RESULTS.BLOCKED` but not `RESULTS.LIMITED` in any context.

May I know for which permission type and on which Platform we get `RESULTS.LIMITED` ?

**Comment by zoontek** [comment]
For now, only PhotoLibrary and Notifications permissions on iOS can be limited.

**Comment by kauamelo** [comment]
I've been wondering the same. I can't manage to get RESULTS.LIMITED on iOS when requesting the status of Notification permissions:
 
`await requestNotifications(['alert']);`

I thought I would get LIMITED when I had "Scheduled Summary" on, allowing the app to show notification only at a certain time. But I still get GRANTED on that case.

I went to Settings > Notifications > My app > Schedule Summary > Set to 'On' > toggled my app:
![IMG_F1DE492E005D-1](https://github.com/zoontek/react-native-permissions/assets/100595841/57d12507-5a83-4941-be7c-1cc52551e2ce)

**Comment by ghost** [comment]
I've been wondering the same. @zoontek, you mentioned it should be possible for Notifications permissions, right? Do you know in which scenario is one supposed to get that?
I can't manage to get RESULTS.LIMITED on iOS when requesting the status of Notification permissions:

`await requestNotifications(['alert']);`

I thought I would get LIMITED when I had "Scheduled Summary" ON, allowing the app to show notification only at a certain time. But I still get GRANTED on that case.

I went to Settings > Notifications > My app > Schedule Summary > Set to 'On' > toggled my app ON:

<img src="https://github.com/zoontek/react-native-permissions/assets/100595841/ce82ac4f-2230-42d8-b98b-dfec45ae9f34" width="300" >

Does anyone know what exactly should I do in order to get RESULTS.LIMITED? Or that option really never happens?

**Comment by zoontek** [comment]
@kauamelo It's when [UNAuthorizationStatus](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus?language=objc) =  [UNAuthorizationStatusEphemeral](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus/unauthorizationstatusephemeral?language=objc) ([link](https://github.com/zoontek/react-native-permissions/blob/3.8.0/ios/Notifications/RNPermissionHandlerNotifications.m#L67))
