### ISSUE TITLE
openLimitedPhotoLibraryPicker Callback

### ISSUE THREAD

**Issue by OmarBasem** [zoontek/react-native-permissions#612]
# Feature request

It would be great to add a callback function or listener for openLimitedPhotoLibraryPicker

## Why it is needed

To know when the user is done

## Possible implementation

Implementation from apple docs: https://developer.apple.com/documentation/photokit/phphotolibrarychangeobserver?language=objc

**Comment by zoontek** [comment]
@OmarBasem I will accept a PR.

Additional infos: https://docs.expo.io/versions/latest/sdk/media-library/#medialibrarypresentpermissionspickerasync
IMHO there is no proper callback, as the promise would resolve on each photo library change.

**Comment by zoontek** [comment]
I'm closing this, since nobody seems really interested in opening a PR.

**Comment by abikbulatov** [comment]
Hello guys, I made it for myself but since here's no solution for this problem I'm happy for share my code with you

disclaimer: I have zero expereince with objective-c/swift hence I made it kinda randomly and my solution might have problems although it's good enough in my case

### What it does?

This module has a listener that triggers every time when amount of photos in a library were changed.   

I set up this listener and then let user choose more photos via `openLimitedPhotoLibraryPicker`, when user changes visible photos for the app we will know it inside the listener and can fetch or delete photos accordingly.

### Installation

`npm i @flekflekerov/react-native-photo-observer@latest`

### Usage
```
import {PhotosChangeObserverModule, RNPhotoObserver} from '@flekflekerov/react-native-photo-observer';

componentDidMount(): void {
  PhotosChangeObserverModule.register();
  RNPhotoObserver.addListener('onPhotosChanged', () => {
    // Do whatever you need when amount of photos were changed
  });
}

componentWillUnmount(): void {
  PhotosChangeObserverModule.unregister();
  RNPhotoObserver.removeAllListeners('onPhotosChanged');
}
```


Source code – https://github.com/xKRUTOIx/react-native-photo-observer/

_____________________________________________________


In case my npm module won't work for you can manually create all needed files and use it right from your project:

Copy the following files to your project:  
1) https://github.com/xKRUTOIx/react-native-photo-observer/blob/main/ios/PhotoChangeEmitter.swift
2) https://github.com/xKRUTOIx/react-native-photo-observer/blob/main/ios/RTCBridge.m
3) https://github.com/xKRUTOIx/react-native-photo-observer/blob/main/ios/reactnativephotoobserver-Bridging-Header.h

With manual approch usage will be a bit different:
```
import {NativeEventEmitter, NativeModules} from 'react-native';

NativeModules.PhotosChangeObserver.register()
this.PhotosObserver = new NativeEventEmitter(NativeModules.PhotosChangeObserver);
this.PhotosObserver.addListener('onPhotosChanged', () => {
    // Do whatever you need when amount of photos were changed
  }
);
```

**Comment by Dassine** [comment]
@xKRUTOIx I was trying your solution but I keep getting `Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.`. Do you have any idea why `NativeModules.PhotosChangeObserver` is null?
