### ISSUE TITLE
Add android permission REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

### ISSUE THREAD

**Issue by ghost** [zoontek/react-native-permissions#632]
# Feature request

It would be great, if you could add the check and request permission for 'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS'.

## Why it is needed

Our app needs the permission to run an infinite background service on android. We implemented a working react native module for testing the code mentioned below. But it would be cool, if it would be part of your library.

## Possible implementation

https://stackoverflow.com/questions/55794316/action-ignore-battery-optimization-settings-need-intent-to-all-apps-list

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-permissions/issues/395
@felix4321 Nobody did a PR, could you?

**Comment by ghost** [comment]
@zoontek Thx for info - I will try the PR!

**Comment by mikehardy** [comment]
@felix4321 careful with this one! has some edge cases apparently where Activity may not exist, and it may cause Play Store rejection https://stackoverflow.com/a/50840603/9910298

It's not a dangerous permission to start, so I think this is more about just opening the settings after giving the user rationale? 

In that case, I think it exists: https://github.com/rasheedk/react-native-disable-battery-optimizations-android

And requesting permission here does not actually make sense, because it is not some restricted permission that the user has to grant, rather it is a settings toggle you need to explain etc

**Comment by zoontek** [comment]
After checking, this is indeed too risky to be put in this library. As it's something exceptional to request this kind of permissions, I think having a second library that only do that makes sense.
