### ISSUE TITLE
PERMISSIONS.IOS.PHOTO_LIBRARY is reporting false status

### ISSUE THREAD

**Issue by SpaghettiC0des** [zoontek/react-native-permissions#673]
### Bug summary

It is returning `RESULTS.UNAVAILABLE` even though I already granted the request.

### Library version

3.2.0

### Environment info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 212.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

The issue is happening on iOS only
iPhone XR iOS 15.2.1
I also tried turning off the screen time and content privacy, but no luck

1. Run the sample code on a physical iOS device.
2. On the first request, grant the permission.
3. After granting the request, go to the settings then **manually** turn off the photo access permission. Go to settings -> search for your app name -> Photos -> None.
4. Re-run the sample code.
5. Check the console, it should log `unavailable` and it should show the alert message.
6. Tap on the `Open settings`, then do step 3, but instead of `None` select `All photos`.
7. Re-run the sample code, check the console, it should log `unavailable` even though you granted access on the settings, manually.

### Reproducible sample code

```js

import {
  check,
  openSettings,
  PERMISSIONS,
  request,
  RESULTS,
} from 'react-native-permissions';
import {Alert} from 'react-native';

const PHOTO_LIBRARY = Platform.select({
  android: PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
  default: PERMISSIONS.IOS.PHOTO_LIBRARY,
});

export async function askCameraPermission() {
  try {
    const status = await check(PHOTO_LIBRARY);

    console.log(`${PHOTO_LIBRARY} is ${status}.`);

    if (status === RESULTS.DENIED) {
      console.log('Requesting permission...');
      const requestStatus = await request(PHOTO_LIBRARY);
      if (requestStatus !== RESULTS.GRANTED) {
        throw {
          permission: PHOTO_LIBRARY,
          status: requestStatus,
          type: 'request',
        };
      }
      return;
    }

    if (status === RESULTS.GRANTED) {
      console.log(`${PHOTO_LIBRARY} is already granted.`);
      return;
    }

    throw {
      permission: PHOTO_LIBRARY,
      status,
      type: 'check',
    };
  } catch (error) {
    Alert.alert('Whoops!', JSON.stringify(error));
  }
}
```

**Comment by SpaghettiC0des** [comment]
@zoontek I updated the steps to reproduce.

**Comment by SpaghettiC0des** [comment]
@zoontek I updated the sample code.

**Comment by zoontek** [comment]
In the code sample you mention camera permission, but in the issue description you mention photos access.
Could you clarify?

**Comment by SpaghettiC0des** [comment]
@zoontek  I updated the sample code. I tested the iOS camera and photo library permission and the issue happens on both of them, if you follow the repro steps.

**Comment by zoontek** [comment]
Just tried your steps and it behaves correctly. I precise I don't use your abstraction but the example app to avoid issues that could came from your code.

1. Run the sample code on a physical iOS device.
2. On the first request, grant the permission.
3. After granting the request, go to the settings then manually turn off the photo access permission. Go to settings -> search for your app name -> Photos -> None.
4. Re-run the sample code.
5. Check the console, it should log unavailable and it should show the alert message.
     👉 **no, it logs `blocked` (which it's supposed to do)**
6. Tap on the Open settings, then do step 3, but instead of None select All photos.
7. Re-run the sample code, check the console, it should log unavailable even though you granted access on the settings, manually.
     👉 **no, it logs `granted` (which it's supposed to do)**

<img src="https://user-images.githubusercontent.com/1902323/151805231-a2860b8d-dc9d-485d-82d4-1fe3c4cd1aca.png" width="400" />

<img src="https://user-images.githubusercontent.com/1902323/151805213-94763909-80d4-44ce-bd9b-3842455c8d5b.png" width="400" />

The library seems to work fine. I would suggest reading the documentation in complete and playing with the example app to understand properly where you made a mistake.

**Comment by efstathiosntonas** [comment]
Hey @zoontek, in my case (and I believe in the same happens in this issue) is that I forgotted to put `PhotoLibrary` in `Podfile`. 

I wasn't in need of the permission after 4 years of using this library and I totally forgot that I had to include the pod resulting in `unvailable`. After adding the pod and cleaned Xcode derived data it worked as a charm. 

I only found out the pod was missing after calling `openPhotoPicker().catch(e => console.log(e))` otherwise I might have never found the issue 🤷‍♂️ 

it would be nice to throw the same error like `openPhotoPicker()` when the pod is missing (I'm using version `4.0.4`)
