### ISSUE TITLE
[question] Better understanding of what setup-ios-permissions is doing

### ISSUE THREAD

**Issue by raid5** [zoontek/react-native-permissions#774]
### Why it is needed?

This is more of a question and not a feature request, but I didn't see that option as one of the issue templates. For iOS, I understand that `setup-ios-permissions` will add the necessary source files to the `RNPermissions.podspec` by reading the permissions listed in the `package.json` (or `reactNativePermissionsIOS.json`). I'm curious why this is necessary and why you can't just always include all of the source files without this step? I'm trying to understand the reasoning for the added setup complexity and the pros/cons of doing it this way.

Thanks!

**Comment by zoontek** [comment]
On iOS, app store reviewers often reject apps that include code to request unused permissions:

- https://github.com/zoontek/react-native-permissions/issues/46
- https://github.com/zoontek/react-native-permissions/issues/240
- https://github.com/zoontek/react-native-permissions/issues/266

The approach has been to create a modular package, [at first with subspecs](https://github.com/zoontek/react-native-permissions/pull/291), then with [a dedicated podspec for each permission](https://github.com/zoontek/react-native-permissions/tree/3.6.1#ios). Each "permission handler" includes the check / request code.

It wasn't perfect since it could create a bunch of caching issues, introduce [the need for a workaround when using `use_frameworks!`](https://github.com/zoontek/react-native-permissions/tree/3.6.1#workaround-for-use_frameworks-issues)

To solve this, we switched to a react native CLI command: `setup-ios-permissions`
It does a pretty simple job: it edits [`node_modules/react-native-permissions/RNPermissions.podspec`](https://github.com/zoontek/react-native-permissions/blob/master/RNPermissions.podspec) `source_files` to add your selected permission handlers directories.

Another benefits is that permissions handlers are now included in the module pod, not in separated ones:

![](https://user-images.githubusercontent.com/1902323/219142183-6348b4ca-ddaa-45ba-b574-08e8685f4608.png)

I hope this answer your question.

**Comment by raid5** [comment]
@zoontek thanks for the detailed explanation! I really appreciate it and love this library <3
