### ISSUE TITLE
Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by osamahafez** [zoontek/react-native-permissions#787]
### Bug summary

I got this error today when running ./gradlew clean on RN 0.63
```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/osamahafez/Software/ThatekWork/mobile/thatek-mobile/node_modules/react-native-permissions/android/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating project ':react-native-permissions'.
> Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-permissions'.
> compileSdkVersion is not specified. Please add it to build.gradle

```

but it was working fine before that.

after further investigation I found a new line was added at 
react-native-permissions/android/build.gradle' line: 62
`namespace = "com.zoontek.rnpermissions"`
that caused the issue

I also upgraded to the latest version but the error persists.

### Library version

3.3.1

### Environment info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 83.55 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
    Python: 2.7.18 - /Users/osamahafez/.pyenv/versions/2.7.18/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. delete node_modules
2. npm install
3. cd android/
4. ./gradlew clean

### Reproducible sample code

```js
the issue is not related to the usage of the package but it's building
```

**Comment by FelipeSSantos1** [comment]
If we confirm the issue is made by my PR I can submit another one changing it to:
```kotlin
// Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace = "com.zoontek.rnpermissions"
    }
```

**Comment by zoontek** [comment]
React native 0.63 is not supported anymore, you can stuck with an old library version (just be sure you pin the version in your package.json)

EDIT: I fixed it using @felipemillhouse / [Flutter's libs](https://github.com/flutter/flutter/issues/125621#issuecomment-1525995461) trick, but also added [a warning in the release](https://github.com/zoontek/react-native-permissions/releases/tag/3.8.3). React Native support policy is supporting the **latest version**, and the **two previous minor series** and we can't expect maintainers to keep compatibility for a version out 3 years ago (+ it's barely used: https://rn-versions.github.io - ~3%)

<img width="777" alt="Screenshot 2023-07-03 at 10 59 49" src="https://github.com/zoontek/react-native-permissions/assets/1902323/8f675722-9a71-4ad4-9bc4-60ff694dc814">

In the future, if it breaks because you are using an outdated, unsupported version of react native, please stick to the latest supported version of this library (`"react-native-permissions": "3.8.0"` ⬅️ fix the version number in your package.json, no `^`) as we cannot keep compat forever.

**Comment by osamahafez** [comment]
@zoontek ok thank you, will keep that in mind
