### ISSUE TITLE
Motion & Fitness remains unavailable after being switched on in Privacy & Security

### ISSUE THREAD

**Issue by captncanary** [zoontek/react-native-permissions#825]
### Bug summary

When Motion & Fitness is switched off in Privacy & Security settings, requesting the permission returns 'unavailable'. If I send the user to Privacy & Security, and they turn on Motion & Fitness, then the user taps the back to app button, then the app is not reset and the permission continues to return unavailable. Restarting the app is required to resolve the issue.
This could be a bug with this package or possibly an iOS bug?
Note this issue is on a physical device running iOS 16.7.1. Testing on a simulator is not possible with Motion & Fitness permissions.

### Library version

3.8.0

### Environment info

```shell
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 543.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/xxxxx/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31, 32, 33, 34
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Install app on iOS physical device.
2. Ensure Motion & Fitness is disabled in Privacy & Security settings
3. Call requestPermission (in code below) - user to sent to Privacy & Security -> Motion & Fitness
4. Switch on Motion & Fitness
5. Click the back button to return to the app
6. Call requestPermission - observe that user is sent to Privacy & Security -> Motion & Fitness again - check permission returned 'unavailable'
7. Kill and restart the app
8. Call request permission - observe user is not sent to the app settings where they can enable Motion & Fitness for the app

### Reproducible sample code

```js
import {
  check,
  PERMISSIONS,
  PermissionStatus,
  request,
} from 'react-native-permissions';

const requestPermission = useCallback(async () => {
    const status = await checkPermission();
    const motionAndFitnessBlocked = status === 'blocked';
    const motionAndFitnessUnavailable = status === 'unavailable';
    
    if (motionAndFitnessUnavailable) {
      await Linking.openURL('App-prefs:Privacy&path=MOTION');
      return;
    }

    if (motionAndFitnessBlocked) {
       await Linking.openSettings();
      return;
    }

    try {
      return await request(PERMISSIONS.IOS.MOTION);
    } catch (error) {
      return 'unavailable';
    }
  }, []);

const checkPermission = async () => {
    try {
      const result = await check(PERMISSIONS.IOS.MOTION);
      return result;
    } catch (error) {
      return 'unavailable' as PermissionStatus;
    }
  };
```

**Comment by zoontek** [comment]
I tried it with a simple experiment and this appear to be an iOS issue. I removed all code in motion permission check except this:

```objc
switch ([CMMotionActivityManager authorizationStatus]) {
  case CMAuthorizationStatusNotDetermined:
    return resolve(RNPermissionStatusNotDetermined);
  case CMAuthorizationStatusRestricted:
    return resolve(RNPermissionStatusRestricted);
  case CMAuthorizationStatusDenied:
    return resolve(RNPermissionStatusDenied);
  case CMAuthorizationStatusAuthorized:
    return resolve(RNPermissionStatusAuthorized);
}
```

Then:
- I perform a check
- It replies with `CMAuthorizationStatusNotDetermined` (which is later mapped to `denied` in this library - it's the android naming)
- I open `Privacy & Security settings` to set `Motion & Fitness` to off
- I go back to the app, perform a check again, it still replies with to `CMAuthorizationStatusNotDetermined` (`denied`)
- I try to perform a request, it does not prompt the user, reply with `blocked`
- After an app restart, everything is OK, the iOS API return the correct value / perform correctly

The issue is similar the other way around:
- I open `Privacy & Security settings` to set `Motion & Fitness` to off
- I perform a check
- It replies with `CMAuthorizationStatusDenied` (which is later mapped to `unavailable` in this library)
- When I try to request the permission, it does not prompt the user, reply with `blocked`
- I open `Privacy & Security settings` to set `Motion & Fitness` to on
- I go back to the app, perform a check again, it still replies with to `CMAuthorizationStatusDenied` (`unavailable`)
- When I try to request the permission, it does not prompt the user, reply with `blocked`
- After an app restart, everything is OK, the iOS API return the correct value / perform correctly

EDIT: related issues https://stackoverflow.com/questions/58403383/cmmotionactivitymanager-authorizationstatus-refresh, https://developer.apple.com/forums/thread/113068, https://developer.apple.com/forums/thread/678138

**Comment by captncanary** [comment]
iOS restarts the app when you change the Motion & Fitness setting for the app itself - perhaps they forgot to do this with the Privacy & Security equivalent.
Thanks for looking into the issue.

**Comment by zoontek** [comment]
I'm closing this as unfortunately we can't do anything 😕
